Temporary fix for big issue bodies, collaborator code reformat
brianoliver/jim pull request #13
Opened 2017-04-13 12:05 UTC by mskd12

Temp fix for #12

2017-04-14 15:27 UTC, brianoliver requested changes

2017-04-14 15:27 UTC, brianoliver commented on jim-github.js
> +                issue.labels.push("ERR: Assignee");
I think you need to ensure the Label is created.  I'm not sure you can simply assign an issue to a label without first creating it.

2017-04-14 15:27 UTC, brianoliver commented on jim-jira.js
> +                issue.labels.push("ERR: Length");
I think you need to ensure the Label is created.  I'm not sure you can simply assign an issue to a label without first creating it.

2017-04-14 15:27 UTC, brianoliver commented on jim-jira.js
> +                        issue.labels.push("ERR: Length");
I think you need to ensure the Label is created.  I'm not sure you can simply assign an issue to a label without first creating it.

2017-04-14 15:27 UTC, brianoliver commented on jim-jira.js
> +            if (issue.body.length >= MAX_BODY_LENGTH) {
Instead of losing the entire message, how about truncating it?   At least that way some/most of the body is included?

2017-04-14 15:27 UTC, brianoliver commented on jim-jira.js
> +                        body = "Comment too long. Unable to import.";
Instead of losing the entire message, how about truncating it?   At least that way some/most of the body is included?

2017-04-16 06:12 UTC, mskd12 commented on jim-github.js
> +                issue.labels.push("ERR: Assignee");
Yes, you can. Just that they will not have any color. You can have a look at how it looks here: https://github.com/mskd12/glassfish/issues/2879
I was doing this earlier for the tags and labels fields also.

2017-04-17 05:30 UTC, mskd12 commented on jim-jira.js
> +            if (issue.body.length >= MAX_BODY_LENGTH) {
I have done that

2017-04-17 11:42 UTC, mskd12 commented on jim-jira.js
> +            affected_versions = []
Added affected versions info also in the issue body

2017-04-17 14:05 UTC, brianoliver commented
Please merge once conflicts are resolved.

2017-04-17 17:28 UTC, merged